name: null
favicon: null
layout_spectrum: 0.07425
typography_spectrum: 0.5
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-21516719-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e6dcc1'
    - '#a49261'
    - '#761b31'
    - '#956572'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: null
    url: null
